#!/usr/bin/env bash
set -euxo pipefail

brew list rg || brew install rg
brew list fd || brew install fd

if [[ ! -d "$HOME/.config" ]]
then
  mkdir -p $HOME/.config
fi

base_path="${PWD}"
nvim_config_path="${base_path}/nvim"

pushd $HOME/.config
ln -s $nvim_config_path .
popd

pushd $HOME
ln  -s $base_path/.ideavimrc .
popd
